micronaut:
  application:
    name: mnStockBroker
  server:
    port: 8080
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
hello:
    controller:
      path: "/hello"
    service:
      greeting: "Hello from Service!"
    config:
      greeting:
        de: "Hallo"
        en: "Hello"
# Json Settings
jackson:
  #property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
    writeDatesWithZoneId: true
    writeDateTimestampsAsNanoseconds: false
  deserialization:
    failOnUnknownProperties: false
  generator:
    #writeNumbersAsStrings: true
    writeNumbersAsStrings: false
    #writeBigDecimalAsPlain: true
    writeBigDecimalAsPlain: false